(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const tabs=$$('.demo-tabs [role=tab]');function selectTab(t){tabs.forEach(x=>{const on=x===t;x.setAttribute('aria-selected',String(on));x.tabIndex=on?0:-1;document.getElementById(x.getAttribute('aria-controls')).hidden=!on;});}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>selectTab(t));t.addEventListener('keydown',e=>{let j;if(e.key==='ArrowRight')j=(i+1)%tabs.length;else if(e.key==='ArrowLeft')j=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')j=0;else if(e.key==='End')j=tabs.length-1;else return;e.preventDefault();selectTab(tabs[j]);tabs[j].focus();});});
const previewFrame=$('[data-demo-frame]'),previewStage=$('[data-preview-stage]');
function fitPreview(){if(!previewFrame||!previewStage||!previewStage.clientWidth)return;const scale=Math.min(1,previewStage.clientWidth/previewFrame.offsetWidth);previewFrame.style.setProperty('--preview-scale',String(scale));const height=Math.ceil(previewFrame.offsetHeight*scale);if(previewStage.style.height!==height+'px')previewStage.style.height=height+'px';}
if(previewFrame&&previewStage){const observer=new ResizeObserver(fitPreview);observer.observe(previewStage);observer.observe(previewFrame);requestAnimationFrame(fitPreview);document.fonts?.ready.then(fitPreview);}
$$('[data-demo-size]').forEach(b=>b.addEventListener('click',()=>{previewFrame.dataset.size=b.dataset.demoSize;$$('[data-demo-size]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('[data-preview-status]').textContent=b.dataset.demoSize==='mobile'?'Vue mobile — écran de 360 px, réduit si nécessaire.':'Vue large — écran de 960 px, réduit si nécessaire.';fitPreview();}));
$$('[data-demo-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-demo-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('.demo-product').forEach(p=>p.hidden=b.dataset.demoFilter!=='Tous'&&p.dataset.category!==b.dataset.demoFilter);}));
const basket=new Map(),currency=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}),cartItems=$('[data-cart-items]');
function cart(){
 let count=0,total=0;cartItems?.replaceChildren();
 basket.forEach((item,name)=>{count+=item.quantity;total+=item.price*item.quantity;
 const li=document.createElement('li'),label=document.createElement('span'),remove=document.createElement('button');
 label.textContent=name+' × '+item.quantity+' — '+currency.format(item.price*item.quantity);
 remove.type='button';remove.className='btn';remove.textContent='Retirer un article';remove.setAttribute('aria-label','Retirer un '+name);
 remove.addEventListener('click',()=>{item.quantity--;if(!item.quantity)basket.delete(name);cart();$('[data-cart-reset]')?.focus()});
 li.append(label,remove);cartItems?.append(li);});
 $('[data-cart-checkout]')?.toggleAttribute('disabled',!count);
 $('[data-cart-status]').textContent=count?'Panier : '+count+' article'+(count>1?'s':'')+' — '+currency.format(total):'Votre panier de démonstration est vide.';
}
$('[data-cart-checkout]')?.addEventListener('click',()=>{const dialog=$('[data-express-dialog]');$('[data-express-summary]').textContent=[...basket].map(([name,item])=>name+' × '+item.quantity).join(' · ');$('[data-express-total]').textContent=currency.format([...basket.values()].reduce((total,item)=>total+item.price*item.quantity,0));$('[data-express-status]').textContent='';$('[data-express-confirm]').disabled=false;dialog.showModal()});
function addProduct(name,price,quantity=1){const item=basket.get(name)||{quantity:0,price};item.quantity+=quantity;basket.set(name,item);cart()}
$$('[data-cart-add]').forEach(b=>b.addEventListener('click',()=>{addProduct(b.dataset.cartAdd,Number(b.dataset.price));b.textContent='Ajouté au panier';setTimeout(()=>b.textContent='Ajouter au panier',1400)}));
document.addEventListener('zed-demo-add',e=>addProduct(e.detail.name,e.detail.price,e.detail.quantity));
$('[data-cart-reset]')?.addEventListener('click',()=>{basket.clear();cart()});
const taskForm=$('[data-task-form]'),taskList=$('[data-task-list]');function taskStatus(){const all=$$('li',taskList);$('[data-task-status]').textContent=all.length+' tâche'+(all.length>1?'s':'')+' — '+all.filter(x=>$('input',x).checked).length+' terminée(s)';}
taskForm?.addEventListener('submit',e=>{e.preventDefault();const input=$('input',taskForm),value=input.value.trim();if(!value){input.setCustomValidity('Saisissez une tâche.');input.reportValidity();return;}input.setCustomValidity('');const li=document.createElement('li'),label=document.createElement('label'),check=document.createElement('input'),span=document.createElement('span'),remove=document.createElement('button');check.type='checkbox';span.textContent=value;remove.type='button';remove.className='btn';remove.textContent='Supprimer';remove.setAttribute('aria-label','Supprimer la tâche : '+value);label.append(check,span);li.append(label,remove);taskList.append(li);check.addEventListener('change',()=>{li.classList.toggle('is-done',check.checked);taskStatus();});remove.addEventListener('click',()=>{li.remove();taskStatus();input.focus();});input.value='';input.focus();taskStatus();});taskForm?.querySelector('input')?.addEventListener('input',e=>e.target.setCustomValidity(''));
$$('[data-palette]').forEach(b=>b.addEventListener('click',()=>{$('[data-identity]').style.setProperty('--demo-accent',b.dataset.palette);$$('[data-palette]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('[data-palette-status]').textContent='Direction '+b.textContent+' sélectionnée.';}));
const solution=$('[data-solution-form]');solution?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(solution),result=$('[data-solution-result]');const n=f.get('native'),r=f.get('roles'),g=f.get('goal');if(!n||!r||!g)return;const answer=n==='yes'?'Application Android et iOS : examiner les fonctions natives et les coûts des deux plateformes.':r==='complex'?'Plateforme sur mesure : préciser les rôles, les données et les processus.':g==='sell'?'Shopify : vérifier le catalogue, les intégrations et les frais récurrents.':g==='service'?'PWA : vérifier la compatibilité des fonctions attendues sur vos appareils.':'Site vitrine : organiser votre offre, vos contenus et la prise de contact.';result.textContent=answer;result.hidden=false;});
const feedback=$('[data-feedback-form]');let draft='';feedback?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(feedback),project=String(f.get('project')||'').trim(),value=String(f.get('feedback')||'').trim();if(!project||value.length<20){const input=$('[name=feedback]',feedback);input.setCustomValidity('Décrivez votre expérience avec au moins 20 caractères utiles.');input.reportValidity();return;}draft='Bonjour ZEDESIGN, voici mon retour.\n\nNom ou alias : '+(String(f.get('name')||'').trim()||'Non précisé')+'\nProjet : '+project+'\n\n'+value+'\n\nRecontact pour une publication : '+(f.has('permission')?'oui':'non');$('[data-feedback-preview]').textContent=draft;$('[data-feedback-send]').href='https://wa.me/33614620757?text='+encodeURIComponent(draft);$('[data-feedback-result]').hidden=false;$('[data-feedback-status]').textContent='Prévisualisation prête. Aucun envoi effectué.';});
feedback?.addEventListener('input',()=>{$('[name=feedback]',feedback).setCustomValidity('');$('[data-feedback-result]').hidden=true;draft='';});
$('[data-feedback-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(draft);$('[data-feedback-status]').textContent='Retour copié.';}catch{$('[data-feedback-status]').textContent='Copie indisponible : sélectionnez le texte de la prévisualisation.';}});
})();

(()=>{
const products=[{"name":"Tote","price":28,"label":"Tote bag Studio","desc":"Un sac en toile pour emporter vos essentiels, avec une signature graphique originale.","spec":"Toile de coton · 38 × 42 cm · Anses longues","options":["Naturel","Forêt","Ardoise"]},{"name":"Affiche","price":24,"label":"Affiche Horizon","desc":"Une composition graphique pour apporter une touche de couleur à votre espace.","spec":"Format A3 · Papier mat 200 g/m² · Sans cadre","options":["Crépuscule","Océan","Soleil"]},{"name":"Carte","price":6,"label":"Carte Correspondance","desc":"Une carte illustrée pour accompagner vos mots et vos petites attentions.","spec":"Format A6 · Papier 300 g/m² · Enveloppe incluse","options":["Sable","Rose","Océan"]}],dialog=document.querySelector('[data-product-dialog]'),express=document.querySelector('[data-express-dialog]');if(!dialog)return;
let selected;const q=s=>document.querySelector(s);
function choose(name){selected=products.find(p=>p.name===name);q('[data-product-title]').textContent=selected.label;q('[data-product-description]').textContent=selected.desc;q('[data-product-price]').textContent=selected.price.toFixed(2).replace('.',',')+' €';q('[data-product-spec]').textContent=selected.spec;const visual=q('[data-product-visual]');visual.replaceChildren(document.querySelector('[data-cart-add="'+name+'"]').closest('article').querySelector('svg').cloneNode(true));const variant=q('[data-product-variant]');variant.replaceChildren(...selected.options.map(text=>{const option=document.createElement('option');option.textContent=text;return option}));q('[data-product-quantity]').value='1';q('[data-product-feedback]').textContent='';}
function buy(name,quantity=1,variant){const p=products.find(p=>p.name===name);q('[data-express-summary]').textContent=p.label+' · '+(variant||p.options[0])+' · Quantité : '+quantity;q('[data-express-total]').textContent=(p.price*quantity).toFixed(2).replace('.',',')+' €';q('[data-express-status]').textContent='';q('[data-express-confirm]').disabled=false;if(dialog.open)dialog.close();express.showModal();}
document.querySelectorAll('[data-product-open]').forEach(b=>b.addEventListener('click',()=>{choose(b.dataset.productOpen);dialog.showModal()}));
document.querySelectorAll('[data-product-express]').forEach(b=>b.addEventListener('click',()=>buy(b.dataset.productExpress)));
q('[data-product-close]').addEventListener('click',()=>dialog.close());q('[data-express-close]').addEventListener('click',()=>express.close());
q('[data-product-buy]').addEventListener('click',()=>{const input=q('[data-product-quantity]');if(input.reportValidity())buy(selected.name,Number(input.value),q('[data-product-variant]').value)});
q('[data-product-add]').addEventListener('click',()=>{const input=q('[data-product-quantity]');if(!input.reportValidity())return;const quantity=Number(input.value),key=selected.name+' · '+q('[data-product-variant]').value;const event=new CustomEvent('zed-demo-add',{detail:{name:key,price:selected.price,quantity}});document.dispatchEvent(event);q('[data-product-feedback]').textContent=quantity+' article(s) ajouté(s) au panier.';});
q('[data-express-confirm]').addEventListener('click',()=>{q('[data-express-status]').textContent='Démonstration terminée. Aucune commande créée, aucun paiement effectué.';q('[data-express-confirm]').disabled=true});
})();
