(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const tabs=$$('.demo-tabs [role=tab]');function selectTab(t){tabs.forEach(x=>{const on=x===t;x.setAttribute('aria-selected',String(on));x.tabIndex=on?0:-1;document.getElementById(x.getAttribute('aria-controls')).hidden=!on;});}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>selectTab(t));t.addEventListener('keydown',e=>{let j;if(e.key==='ArrowRight')j=(i+1)%tabs.length;else if(e.key==='ArrowLeft')j=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')j=0;else if(e.key==='End')j=tabs.length-1;else return;e.preventDefault();selectTab(tabs[j]);tabs[j].focus();});});
const previewFrame=$('[data-demo-frame]'),previewStage=$('[data-preview-stage]');
function fitPreview(){if(!previewFrame||!previewStage||!previewStage.clientWidth)return;const scale=Math.min(1,previewStage.clientWidth/previewFrame.offsetWidth);previewFrame.style.setProperty('--preview-scale',String(scale));const height=Math.ceil(previewFrame.offsetHeight*scale);if(previewStage.style.height!==height+'px')previewStage.style.height=height+'px';}
if(previewFrame&&previewStage){const observer=new ResizeObserver(fitPreview);observer.observe(previewStage);observer.observe(previewFrame);requestAnimationFrame(fitPreview);document.fonts?.ready.then(fitPreview);}
$$('[data-demo-size]').forEach(b=>b.addEventListener('click',()=>{previewFrame.dataset.size=b.dataset.demoSize;$$('[data-demo-size]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('[data-preview-status]').textContent=b.dataset.demoSize==='mobile'?'Vue mobile — écran de 360 px, réduit si nécessaire.':'Vue large — écran de 960 px, réduit si nécessaire.';fitPreview();}));
$$('[data-demo-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-demo-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('.demo-product').forEach(p=>p.hidden=b.dataset.demoFilter!=='Tous'&&p.dataset.category!==b.dataset.demoFilter);}));
let count=0,total=0;const currency=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'});const cart=()=>{$('[data-cart-status]').textContent='Panier : '+count+' article'+(count>1?'s':'')+' — '+currency.format(total);};
$$('[data-cart-add]').forEach(b=>b.addEventListener('click',()=>{count++;total+=Number(b.dataset.price);cart();}));$('[data-cart-reset]')?.addEventListener('click',()=>{count=0;total=0;cart();});
const taskForm=$('[data-task-form]'),taskList=$('[data-task-list]');function taskStatus(){const all=$$('li',taskList);$('[data-task-status]').textContent=all.length+' tâche'+(all.length>1?'s':'')+' — '+all.filter(x=>$('input',x).checked).length+' terminée(s)';}
taskForm?.addEventListener('submit',e=>{e.preventDefault();const input=$('input',taskForm),value=input.value.trim();if(!value){input.setCustomValidity('Saisissez une tâche.');input.reportValidity();return;}input.setCustomValidity('');const li=document.createElement('li'),label=document.createElement('label'),check=document.createElement('input'),span=document.createElement('span'),remove=document.createElement('button');check.type='checkbox';span.textContent=value;remove.type='button';remove.className='btn';remove.textContent='Supprimer';remove.setAttribute('aria-label','Supprimer la tâche : '+value);label.append(check,span);li.append(label,remove);taskList.append(li);check.addEventListener('change',()=>{li.classList.toggle('is-done',check.checked);taskStatus();});remove.addEventListener('click',()=>{li.remove();taskStatus();input.focus();});input.value='';input.focus();taskStatus();});taskForm?.querySelector('input')?.addEventListener('input',e=>e.target.setCustomValidity(''));
$$('[data-palette]').forEach(b=>b.addEventListener('click',()=>{$('[data-identity]').style.setProperty('--demo-accent',b.dataset.palette);$$('[data-palette]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('[data-palette-status]').textContent='Direction '+b.textContent+' sélectionnée.';}));
const solution=$('[data-solution-form]');solution?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(solution),result=$('[data-solution-result]');const n=f.get('native'),r=f.get('roles'),g=f.get('goal');if(!n||!r||!g)return;const answer=n==='yes'?'Application Android et iOS : examiner les fonctions natives et les coûts des deux plateformes.':r==='complex'?'Plateforme sur mesure : préciser les rôles, les données et les processus.':g==='sell'?'Shopify : vérifier le catalogue, les intégrations et les frais récurrents.':g==='service'?'PWA : vérifier la compatibilité des fonctions attendues sur vos appareils.':'Site vitrine : organiser votre offre, vos contenus et la prise de contact.';result.textContent=answer;result.hidden=false;});
const feedback=$('[data-feedback-form]');let draft='';feedback?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(feedback),project=String(f.get('project')||'').trim(),value=String(f.get('feedback')||'').trim();if(!project||value.length<20){const input=$('[name=feedback]',feedback);input.setCustomValidity('Décrivez votre expérience avec au moins 20 caractères utiles.');input.reportValidity();return;}draft='Bonjour ZEDESIGN, voici mon retour.\n\nNom ou alias : '+(String(f.get('name')||'').trim()||'Non précisé')+'\nProjet : '+project+'\n\n'+value+'\n\nRecontact pour une publication : '+(f.has('permission')?'oui':'non');$('[data-feedback-preview]').textContent=draft;$('[data-feedback-send]').href='https://wa.me/33614620757?text='+encodeURIComponent(draft);$('[data-feedback-result]').hidden=false;$('[data-feedback-status]').textContent='Prévisualisation prête. Aucun envoi effectué.';});
feedback?.addEventListener('input',()=>{$('[name=feedback]',feedback).setCustomValidity('');$('[data-feedback-result]').hidden=true;draft='';});
$('[data-feedback-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(draft);$('[data-feedback-status]').textContent='Retour copié.';}catch{$('[data-feedback-status]').textContent='Copie indisponible : sélectionnez le texte de la prévisualisation.';}});
})();
